version: '2'
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
  eslint:
    enabled: true
    channel: 'eslint-7'
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
  - node_modules/
  - '**/test/'
