export const SET_ACCOMMODATIONS = 'SET_ACCOMMODATIONS';
export const SET_LOCATIONS = 'SET_LOCATIONS';
export const SET_TRIP_REQUESTS = 'SET_TRIP_REQUESTS';
export const SET_TRIPS_OWNERS = 'SET_TRIPS_OWNERS';
export const ACCOMMODATIONS_ERROR = 'ACCOMMODATIONS_ERROR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const LOGOUT = 'LOGOUT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIRURE = 'USER_REGISTER_FAIRURE';

// LOGIN ACTION TYPES
export const LoginTypes = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
};
